### ISSUE TITLE
Code crashing 

### ISSUE THREAD

**Issue by Oussamab21** [imguangyu/FedPerfix#2]
Hi thanks for sharing the code of this great contribution, I was running the code and I am getting this error( I commented the lines related to Wandb) thanks in advance

  Traceback (most recent call last):
  File "/home/at17760@ens.ad.etsmtl.ca/oussama/FedPerfix/FedPerfix-main/system/main.py", line 519, in <module>
    thread_outputs = pool.map(run_clients, [client_infos for _ in range(args.num_threads)])
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 540, in _handle_tasks
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 206, in send
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
  File "/home/at17760@ens.ad.etsmtl.ca/oussama/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 370, in reduce_storage
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 198, in DupFd
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/usr/lib/python3.10/weakref.py", line 667, in _exitfunc
  File "/usr/lib/python3.10/weakref.py", line 591, in __call__
  File "/usr/lib/python3.10/tempfile.py", line 998, in _cleanup
  File "/usr/lib/python3.10/tempfile.py", line 994, in _rmtree
  File "/usr/lib/python3.10/shutil.py", line 721, in rmtree
  File "/usr/lib/python3.10/shutil.py", line 718, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/tmprx6w78cbwandb'
Traceback (most recent call last):
  File "/usr/lib/python3.10/weakref.py", line 667, in _exitfunc
  File "/usr/lib/python3.10/weakref.py", line 591, in __call__
  File "/usr/lib/python3.10/tempfile.py", line 998, in _cleanup
  File "/usr/lib/python3.10/tempfile.py", line 994, in _rmtree
  File "/usr/lib/python3.10/shutil.py", line 721, in rmtree
  File "/usr/lib/python3.10/shutil.py", line 718, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/tmp5dc9kcpdwandb-artifacts'
Traceback (most recent call last):
  File "/usr/lib/python3.10/weakref.py", line 667, in _exitfunc
  File "/usr/lib/python3.10/weakref.py", line 591, in __call__
  File "/usr/lib/python3.10/tempfile.py", line 998, in _cleanup
  File "/usr/lib/python3.10/tempfile.py", line 994, in _rmtree
  File "/usr/lib/python3.10/shutil.py", line 721, in rmtree
  File "/usr/lib/python3.10/shutil.py", line 718, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/tmp9pbqy4g_wandb-media'
Traceback (most recent call last):
  File "/usr/lib/python3.10/weakref.py", line 667, in _exitfunc
  File "/usr/lib/python3.10/weakref.py", line 591, in __call__
  File "/usr/lib/python3.10/tempfile.py", line 998, in _cleanup
  File "/usr/lib/python3.10/tempfile.py", line 994, in _rmtree
  File "/usr/lib/python3.10/shutil.py", line 721, in rmtree
  File "/usr/lib/python3.10/shutil.py", line 718, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/tmp3gb8f0dawandb-media'
Exception ignored in: <function Pool.__del__ at 0x7f239509ce50>
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 271, in __del__
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 371, in put
AttributeError: 'NoneType' object has no attribute 'dumps'

**Comment by imguangyu** [comment]
Sorry for the late response. It seems the multi-processing doesn't work correctly. Could you please try to switch to Python 3.8? Thanks for following our work.

**Comment by Karl-Chung** [comment]
Thank you for your interesting work and for providing the code. However, I am experiencing the similar issue. For your information, I am using Python 3.8.0 with four RTX 3090 GPUs with default setting you provided


`-------------Round number: 0-------------

Evaluate global model
Global Test Accurancy: 0.0000
Global Test AUC: 0.0000
Averaged Test Accurancy: 0.0000
Std Test Accurancy: 0.0000
Averaged Test AUC: 0.0000
Std Test AUC: 0.0000
Thread 1 initialized!
Thread 2 initialized!
Traceback (most recent call last):
  File "/home/usr/anaconda3/envs/ppfl/lib/python3.8/multiprocessing/resource_sharer.py", line 149, in _serve
    send(conn, destination_pid)
  File "/home/usr/anaconda3/envs/ppfl/lib/python3.8/multiprocessing/resource_sharer.py", line 50, in send
    reduction.send_handle(conn, new_fd, pid)
  File "/home/usr/anaconda3/envs/ppfl/lib/python3.8/multiprocessing/reduction.py", line 183, in send_handle
    with socket.fromfd(conn.fileno(), socket.AF_UNIX, socket.SOCK_STREAM) as s:
  File "/home/usr/anaconda3/envs/ppfl/lib/python3.8/socket.py", line 543, in fromfd
    nfd = dup(fd)
OSError: [Errno 24] Too many open files
Thread 3 initialized!
Thread 4 initialized!`

**Comment by imguangyu** [comment]
@Karl-Chung Would you mind trying to reduce the number of threads for me? I'm trying to figure out why it happens. Thanks!

**Comment by countingeyes** [comment]
Hi！ I am experiencing a similar issue！ Have you solved this problem?

**Comment by countingeyes** [comment]
> Thank you for your interesting work and for providing the code. However, I am experiencing the similar issue. For your information, I am using Python 3.8.0 with four RTX 3090 GPUs with default setting you provided
> 
> `-------------Round number: 0-------------
> 
> Evaluate global model Global Test Accurancy: 0.0000 Global Test AUC: 0.0000 Averaged Test Accurancy: 0.0000 Std Test Accurancy: 0.0000 Averaged Test AUC: 0.0000 Std Test AUC: 0.0000 Thread 1 initialized! Thread 2 initialized! Traceback (most recent call last): File "/home/usr/anaconda3/envs/ppfl/lib/python3.8/multiprocessing/resource_sharer.py", line 149, in _serve send(conn, destination_pid) File "/home/usr/anaconda3/envs/ppfl/lib/python3.8/multiprocessing/resource_sharer.py", line 50, in send reduction.send_handle(conn, new_fd, pid) File "/home/usr/anaconda3/envs/ppfl/lib/python3.8/multiprocessing/reduction.py", line 183, in send_handle with socket.fromfd(conn.fileno(), socket.AF_UNIX, socket.SOCK_STREAM) as s: File "/home/usr/anaconda3/envs/ppfl/lib/python3.8/socket.py", line 543, in fromfd nfd = dup(fd) OSError: [Errno 24] Too many open files Thread 3 initialized! Thread 4 initialized!`

Hi！ I am experiencing a similar issue! Have you solved this problem?

**Comment by imguangyu** [comment]
> > Thank you for your interesting work and for providing the code. However, I am experiencing the similar issue. For your information, I am using Python 3.8.0 with four RTX 3090 GPUs with default setting you provided
> > `-------------Round number: 0-------------
> > Evaluate global model Global Test Accurancy: 0.0000 Global Test AUC: 0.0000 Averaged Test Accurancy: 0.0000 Std Test Accurancy: 0.0000 Averaged Test AUC: 0.0000 Std Test AUC: 0.0000 Thread 1 initialized! Thread 2 initialized! Traceback (most recent call last): File "/home/usr/anaconda3/envs/ppfl/lib/python3.8/multiprocessing/resource_sharer.py", line 149, in _serve send(conn, destination_pid) File "/home/usr/anaconda3/envs/ppfl/lib/python3.8/multiprocessing/resource_sharer.py", line 50, in send reduction.send_handle(conn, new_fd, pid) File "/home/usr/anaconda3/envs/ppfl/lib/python3.8/multiprocessing/reduction.py", line 183, in send_handle with socket.fromfd(conn.fileno(), socket.AF_UNIX, socket.SOCK_STREAM) as s: File "/home/usr/anaconda3/envs/ppfl/lib/python3.8/socket.py", line 543, in fromfd nfd = dup(fd) OSError: [Errno 24] Too many open files Thread 3 initialized! Thread 4 initialized!`
> 
> Hi！ I am experiencing a similar issue! Have you solved this problem?

Hi! Thanks for following our work. Could you please try the following solution:
1. Run `ulimit -n` in the bash to check the current file limit.
2. Use `ulimit -n 4096` to set a large number (e.g., 4096) as the limit.

**Comment by countingeyes** [comment]
> 1. ulimit -n

Hi！Thank you for your kind advice! I tried to set a large number as 4096 but the error still exists.   

All the thread n initialized in my code, but the problems about pool.map.


Details below.
####################################################################################
Finished creating server and clients.
Thread 3 initialized!
Thread 1 initialized!
Thread 4 initialized!
Thread 2 initialized!

-------------Round number: 0-------------

Evaluate global model
Global Test Accurancy: 0.0000
Global Test AUC: 0.0000
Averaged Test Accurancy: 0.0000
Std Test Accurancy: 0.0000
Averaged Test AUC: 0.0000
Std Test AUC: 0.0000
Traceback (most recent call last):
  File "main.py", line 509, in <module>
  File "/home/lyq/.conda/envs/fed/lib/python3.8/multiprocessing/pool.py", line 364, in map
  File "/home/lyq/.conda/envs/fed/lib/python3.8/multiprocessing/pool.py", line 771, in get
  File "/home/lyq/.conda/envs/fed/lib/python3.8/multiprocessing/pool.py", line 537, in _handle_tasks
  File "/home/lyq/.conda/envs/fed/lib/python3.8/multiprocessing/connection.py", line 206, in send
  File "/home/lyq/.conda/envs/fed/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/lyq/.conda/envs/fed/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 366, in reduce_storage
RuntimeError: unable to open shared memory object </torch_55916_1796798897_361> in read-write mode: Too many open files (24)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/lyq/.conda/envs/fed/lib/python3.8/shutil.py", line 712, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/tmp_wr3gelcwandb-media'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/lyq/.conda/envs/fed/lib/python3.8/shutil.py", line 712, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/tmp6s2v0z0jwandb-artifacts'
Traceback (most recent call last):
  File "/home/lyq/.conda/envs/fed/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/lyq/.conda/envs/fed/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/lyq/.conda/envs/fed/lib/python3.8/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/lyq/.conda/envs/fed/lib/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/lyq/.conda/envs/fed/lib/python3.8/shutil.py", line 631, in _rmtree_safe_fd
    onerror(os.scandir, path, sys.exc_info())
  File "/home/lyq/.conda/envs/fed/lib/python3.8/shutil.py", line 627, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
OSError: [Errno 24] Too many open files: '/tmp/pymp-wlha1qxo'
Exception ignored in: <function Pool.__del__ at 0x7fd0c3db7670>
Traceback (most recent call last):
  File "/home/lyq/.conda/envs/fed/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/lyq/.conda/envs/fed/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: driver shutting down (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: driver shutting down (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: driver shutting down (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
...

###################################################################################


Have you seen this problem?

**Comment by countingeyes** [comment]
I found that I could train, but the training was not stable. The above problems might occur during the training. What do you think about this？

**Comment by imguangyu** [comment]
> I found that I could train, but the training was not stable. The above problems might occur during the training. What do you think about this？

Can you try to reduce the total number of clients and see if it still happens?

**Comment by lemontree888** [comment]
Attempt to add the following code at the beginning of the main. py file?
import torch.multiprocessing
torch.multiprocessing.set_sharing_strategy('file_system')

**Comment by XWenyan** [comment]
您好，我按照默认设置取得的训练结果如下，不知道可能是哪里出了问题，请问您可以给出一些建议吗？<img width="322" height="215" alt="Image" src="https://github.com/user-attachments/assets/0f9fb063-7df2-4e13-996c-e1f43b84f7a7" />

**Comment by lemontree888** [comment]
> 您好，我按照默认设置取得的训练结果如下，不知道可能是哪里出了问题，请问您可以给出一些建议吗？<img alt="Image" width="322" height="215" src="https://private-user-images.githubusercontent.com/128778838/507500374-0f9fb063-7df2-4e13-996c-e1f43b84f7a7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE4MTIzMTcsIm5iZiI6MTc2MTgxMjAxNywicGF0aCI6Ii8xMjg3Nzg4MzgvNTA3NTAwMzc0LTBmOWZiMDYzLTdkZjItNGUxMy05OTZjLWUxZjQzYjg0ZjdhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAzMFQwODEzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmVkZGIyMDNkODMzMDE4ZDFjYzQ2N2JmN2I1YzI1NjBlNzdhYThhYTg0MjUxMjNiODliMDdhMzFhMjA1YzE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GA_Rn2iWLSOKPLGL3aEaSS1SWuGyfCC5PbAowsBri8M">

这位痒痒鼠玩家，这个有点久了，都忘记训练结果是什么了，给你看deepseek的建议（doge

<img width="593" height="230" alt="Image" src="https://github.com/user-attachments/assets/2b855a2d-dc5c-4a73-af9e-570d0dbacf91" />

**Comment by imguangyu** [comment]
> 您好，我按照默认设置取得的训练结果如下，不知道可能是哪里出了问题，请问您可以给出一些建议吗？<img width="322" height="215" alt="Image" src="https://github.com/user-attachments/assets/0f9fb063-7df2-4e13-996c-e1f43b84f7a7" />

Hi, since this is a PFL work, we only care about the averaged client accuracy and std here, and all other metrics are for reference. If you didn't change any config, your results will be FedAVG on CIFAR-100, which are pretty close to our reported results in the paper (23.29）. Feel free to try different methods!

**Comment by XWenyan** [comment]
> > 您好，我按照默认设置取得的训练结果如下，不知道可能是哪里出了问题，请问您可以给出一些建议吗？<img alt="Image" width="322" height="215" src="https://private-user-images.githubusercontent.com/128778838/507500374-0f9fb063-7df2-4e13-996c-e1f43b84f7a7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE4NzkwMTAsIm5iZiI6MTc2MTg3ODcxMCwicGF0aCI6Ii8xMjg3Nzg4MzgvNTA3NTAwMzc0LTBmOWZiMDYzLTdkZjItNGUxMy05OTZjLWUxZjQzYjg0ZjdhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAzMVQwMjQ1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmFiMzM3NTYxZGYxYjRkOWRjZmZlNjEwZmY2NWYwZTM0ZGNjY2JmODYwNDI4YThlMTI0MjgwZjc0YTAyOTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WVpLMcoVtpbNMmo91r6Xnq24jdMvq3Ad69Mvcn52aRQ">
> 
> Hi, since this is a PFL work, we only care about the averaged client accuracy and std here, and all other metrics are for reference. If you didn't change any config, your results will be FedAVG on CIFAR-100, which are pretty close to our reported results in the paper (23.29）. Feel free to try different methods!

Appreciate your reply! I overlooked the fact that FedAVG was chosen; that was my carelessness.
